### PR TITLE
Angular-tomitribe-sortable component

### PR DESCRIPTION
**Pull request by Dexmaster**
Init commit

### CODE REVIEW

**Comment by r-tt** [comment]
Not sure on the overall component but at least you missed to update bundle.ts mapping for the new showcase route

**Comment by Dexmaster** [comment]
I knew it that's why on meeting I said that I need to discuss bundling

**Comment by r-tt** [comment]
why dont we just rely on https://github.com/schartier/angular-sortable ?

**Comment by Dexmaster** [comment]
read Related attributes

**Comment by r-tt** [comment]
looks equivalent, not sure the use case we can meet requiring a new untested wrapper

**Comment by Dexmaster** [comment]
And and lot's of other things he adds css as a main part of component
It's based on jquery-ui, Jquery is still used he just wrapped it into  angular.module('sortable', []) from line 306 before that is just js prototyping.

**Comment by Dexmaster** [comment]
Check test folder it's just a clone of ui.sortable, without really checking or testing

**Comment by Dexmaster** [comment]
it's "untested" too

**Pull request merged**
